version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.08
    steps:
      - checkout
      - run:
          command: ./gradlew test
  android-test:
    parameters:
      system-image:
        type: string
        default: system-images;android-30;google_apis;x86
    executor:
      name: android/android-machine
      tag: 2023.07.1
      resource-class: large
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          no-window: true
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-30;google_apis;x86
workflows:
  build_and_test:
    jobs:
      - build
      - android-test